"""
rag_state.py

This module defines the shared state used by the LangGraph workflow.

Think of the state as a shared notebook.

Every node in the graph can:
    • Read information from it
    • Update information
    • Pass it to the next node

Without a state object, the nodes would not be able
to communicate with each other.
"""

from typing import List

from pydantic import BaseModel
from langchain.schema import Document


class RAGState(BaseModel):
    """
    Shared state for the RAG workflow.

    This object travels through every node in the graph.

    Example Workflow

        User Question
              │
              ▼
        Retrieve Node
              │
              ▼
        Generate Node
              │
              ▼
           Final Answer

    At every step, this same state object is updated.
    """

    # User's question
    question: str

    # Documents retrieved from the vector database
    retrieved_docs: List[Document] = []

    # Final answer generated by the LLM
    answer: str = ""